### PR TITLE
Add option to write to file

### PR DESCRIPTION
**Pull request by AdityaAS**

### CODE REVIEW

**Comment by miku** [comment]
@AdityaAS, sorry for looking at this just now.

The basic functionality "writing to a file" is covered just redirecting stdout to a file.

```
$ solrdump > file
```

Do you have a use case, where this would not suffice?

**Comment by miku** [comment]
@AdityaAS, thanks for your work. Allow me me elaborate a bit. The `-output` flag is missing because it is not needed, if fact it would create a second way to do something, which is unnecessary 90% of the time or even more.

This [blogpost about wiriting unix tools](https://monkey.org/~marius/unix-tools-hints.html) hints at the key idea: 

> “One thing well” misses the point: it should be “One thing well AND COMPOSES WELL”

And writing to stdout is the key to composability, at least in the realm of the command line (one example is shown in the [README](https://github.com/ubleipzig/solrdump#instant-search-as-one-liner).

Please convince me that adding an `-output` flag is worthwhile, as I remain unconvinced.

**Comment by AdityaAS** [comment]
@miku  I had a use case where I needed the file write option inside the code itself. I was using this script from another project and thought it'd be useful.
The later commits (the python impl etc I wrote for my convenience. Was not aware that they were being added to the PR)

**Comment by miku** [comment]
@AdityaAS, thanks for the clarification and I hope I did not seem too dogmatic. Most programming language libraries for subprocesses would be able to handle redirects, or even tie into the standard streams as well, meaning, it would probably make a subprocess call a bit more elegant as processes could exchange data, without having to physically write a file.

Anyway, I hope it's fine. Thanks again for putting in the thoughts.

**Pull request closed without merging**
